version: 2
services:
  app:
    image: whatdafox/php-fpm:latest
    volumes:
      - .:/var/www/html
    ports:
      - '${APP_PORT}:80'
    networks:
      - app-net
  mysql:
    image: mysql:5.7
    volumes:
      - mysqldata:/var/lib/mysql
    ports:
      - '${DB_PORT}:3306'
    networks:
      - app-net
  redis:
    image: redis:latest
    volumes:
      - redisdata:/data
    networks:
      - app-net
networks:
  app-net:
    driver: local
volumes:
  mysqldata:
    driver: local
  redisdata:
    driver: local
